### ISSUE TITLE
💗 your screeenshot!

### ISSUE THREAD

**Issue by PySimpleGUI** [danodx/PGen#1]
Thank you for posting a screenshot in your readme!  ![image](https://user-images.githubusercontent.com/46163555/162321277-6145ead7-e1af-4272-b077-9a049932e920.png)

They always grab visitors' attention.  You've got a GUI after all.

Here's a tip for you in case you don't want to put the screenshot in your repo itself....   You can put the screenshot into a GitHub Issue, just like this issue.

You can literally paste the image into an Issue and then grab the line of text that GitHub added and paste it into your readme.

![pic](https://user-images.githubusercontent.com/46163555/162322800-3d2f5fa0-3803-4ba3-b602-b6e2b1e43a32.png)

The above image added this line of markdown text into the comment:
```
![pic](https://user-images.githubusercontent.com/46163555/162322800-3d2f5fa0-3803-4ba3-b602-b6e2b1e43a32.png)
```

If you paste that into your readme.md file, then you'll get the same image as the one currently in your repo.  I'm working on building some tools into PySimpleGUI to make this even easier.

Thanks for the motivation!  I really enjoy seeing what users are making... It's good stuff!

**Comment by danosyrus** [comment]
Always welcome
❤️ Thanks for the tip!
